env:
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  no-console: off,
  import/extensions: off,
  consistent-return: off,
  no-use-before-define: off,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
}
