env:
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: off,
  import/extensions: off,
  consistent-return: off,
}
